### ISSUE TITLE
Dungeon Room Key journal page type not available in v12 Shadowdark

### ISSUE THREAD

**Issue by sirkerry** [wyrmisis/bx-factions#10]
Was using the Factions and Dungeon Room Key journal pages with the Shadowdark  game system in v11, switched over to v12 and while the Factions journal page type shows and is still useable, the Dungeon Room Key (and OSE Class page) no longer show as available journal page types.

**Comment by wyrmisis** [comment]
The OSE class page not showing up is expected behavior, at least as the module is right now. I think I did that because I thought I had some OSE-specific stuff in there.

The room key pages not showing up? That's weird. I still haven't updated my Foundry installs to v12 (my non-work dev time has been severely limited, up toward nonexistent), as the Old School Essentials system still has some issues with v12, and I haven't been able to help out with that, either.

I'll do what I can, once I can. Sorry for the inconvenience, as well as this possibly taking a bit of time for me to get to.

**Comment by sirkerry** [comment]
No worries. Just out of curiosity, I tried this module with OSE under v12 and it's doing the same thing - just showing Factions and no Dungeon Room Key or OSE Class pages as options.

I've got FVTT setup to run 3 different versions (v10, v11, and v12) depending on what I need/want to run.

**Comment by wyrmisis** [comment]
Any chance you could give this a go with 0.3.7 and let me know what you see?

**Comment by sirkerry** [comment]
Okay, I tried 0.3.7 in v12.331 with Shadowdark and OSE - it's showing all 3 journal page options in both and allows the creation of said journal pages. Thank you.
